apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi:8080"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "xiaotech"
  volumetype: "replicate:2"
